### ISSUE TITLE
03/16 회의 내용 관련 추가

### ISSUE THREAD

**Issue by NohMyungWook** [match-gg/MATCH_BE#29]
## 작업 내용
> 3/16 회의와 관련된 내용을 추가합니다.
## Todo-list
- [x] 게시글 찾는 방식 파라미터로 필터링이 가능하게끔
- [x] payload에 representative 추가
- [x] 게시글에 created 함께 보내줘야함. 게시글 만료 처리를 하기 위함.
