### ISSUE TITLE
채팅방 강퇴 기능 추가 및 bug fix

### ISSUE THREAD

**Issue by NohMyungWook** [match-gg/MATCH_BE#41]
## 작업 내용
> 채팅방 강퇴 api 제작 및, 기존 api 새 디자인 + bug fix
## Todo-list
- [ ] 채팅방 나가기 시 유저 검증 코드 리팩토
- [ ] banList 기능 추가
- [ ] kick 관련 api 제작
